In [1]:
#importing important libraries
# Data manipulation
import pandas as pd
import numpy as np

# Train-test split
from sklearn.model_selection import train_test_split

# Preprocessing 
from sklearn.preprocessing import StandardScaler

# Base models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import (
    RandomForestClassifier,
    GradientBoostingClassifier,
    AdaBoostClassifier,
    ExtraTreesClassifier
)
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

# Evaluation metrics
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

In [2]:
df = pd.read_excel("OneDrive/Desktop/4th sem/DVZ/Book1.xlsx")

#Exploratory Data Analysis
print(df.shape)
df.head()

(6418, 32)

,Customer_ID,Gender,Age,Married,State,Number_of_Referrals,Tenure_in_Months,Value_Deal,Phone_Service,Multiple_Lines,...,Payment_Method,Monthly_Charge,Total_Charges,Total_Refunds,Total_Extra_Data_Charges,Total_Long_Distance_Charges,Total_Revenue,Customer_Status,Churn_Category,Churn_Reason
0,15776-UTT,Female,38,Yes,Uttar Pradesh,1,19,NaN,No,NaN,...,Bank Withdrawal,45.05,2560.1,0.0,0,0.0,2560.1,Stayed,NaN,NaN
1,49302-GUJ,Female,47,No,Gujarat,14,4,NaN,No,NaN,...,Credit Card,61.25,1993.2,0.0,0,0.0,1993.2,Stayed,NaN,NaN
2,39181-WES,Male,54,Yes,West Bengal,10,7,NaN,No,NaN,...,Credit Card,45.80,1147.0,0.0,0,0.0,1147.0,Stayed,NaN,NaN
3,22915-MAH,Female,41,Yes,Maharashtra,10,23,NaN,No,NaN,...,Bank Withdrawal,56.60,3789.2,0.0,0,0.0,3789.2,Stayed,NaN,NaN
4,76712-AND,Female,42,No,Andhra Pradesh,12,2,NaN,No,NaN,...,Credit Card,45.00,2196.3,0.0,0,0.0,2196.3,Stayed,NaN,NaN

In [3]:
#Identifying empty values
print(df.info())
print("\n")
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6418 entries, 0 to 6417
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Customer_ID                  6418 non-null   object
 1   Gender                       6418 non-null   object
 2   Age                          6418 non-null   int64
 3   Married                      6418 non-null   object
 4   State                        6418 non-null   object
 5   Number_of_Referrals          6418 non-null   int64
 6   Tenure_in_Months             6418 non-null   int64
 7   Value_Deal                   2870 non-null   object
 8   Phone_Service                6418 non-null   object
 9   Multiple_Lines               5796 non-null   object
 10  Internet_Service             6418 non-null   object
 11  Internet_Type                6418 non-null   object
 12  Online_Security              5028 non-null   object
 13  Online_Backup                5028 non-null   object
 14  Device_Protection_Plan       5028 non-null   object
 15  Premium_Support              5028 non-null   object
 16  Streaming_TV                 5028 non-null   object
 17  Streaming_Movies             5028 non-null   object
 18  Streaming_Music              5028 non-null   object
 19  Unlimited_Data               5028 non-null   object
 20  Contract                     6418 non-null   object
 21  Paperless_Billing            6418 non-null   object
 22  Payment_Method               6418 non-null   object
 23  Monthly_Charge               6418 non-null   float64
 24  Total_Charges                6418 non-null   float64
 25  Total_Refunds                6418 non-null   float64
 26  Total_Extra_Data_Charges     6418 non-null   int64
 27  Total_Long_Distance_Charges  6418 non-null   float64
 28  Total_Revenue                6418 non-null   float64
 29  Customer_Status              6418 non-null   object
 30  Churn_Category               1732 non-null   object
 31  Churn_Reason                 1732 non-null   object
dtypes: float64(5), int64(4), object(23)
memory usage: 1.6+ MB
None


Customer_ID                       0
Gender                            0
Age                               0
Married                           0
State                             0
Number_of_Referrals               0
Tenure_in_Months                  0
Value_Deal                     3548
Phone_Service                     0
Multiple_Lines                  622
Internet_Service                  0
Internet_Type                     0
Online_Security                1390
Online_Backup                  1390
Device_Protection_Plan         1390
Premium_Support                1390
Streaming_TV                   1390
Streaming_Movies               1390
Streaming_Music                1390
Unlimited_Data                 1390
Contract                          0
Paperless_Billing                 0
Payment_Method                    0
Monthly_Charge                    0
Total_Charges                     0
Total_Refunds                     0
Total_Extra_Data_Charges          0
Total_Long_Distance_Charges       0
Total_Revenue                     0
Customer_Status                   0
Churn_Category                 4686
Churn_Reason                   4686
dtype: int64

In [4]:
#Filling empty values
cols_to_fill = [
    'Value_Deal',
    'Multiple_Lines',
    'Online_Security',
    'Online_Backup',
    'Device_Protection_Plan',
    'Premium_Support',
    'Streaming_TV',
    'Streaming_Movies',
    'Streaming_Music',
    'Unlimited_Data',
    'Churn_Category',
    'Churn_Reason'
]

for col in cols_to_fill:
    df[col] = df[col].fillna('NA')

In [5]:
#verification
print(df.isnull().sum())

Customer_ID                    0
Gender                         0
Age                            0
Married                        0
State                          0
Number_of_Referrals            0
Tenure_in_Months               0
Value_Deal                     0
Phone_Service                  0
Multiple_Lines                 0
Internet_Service               0
Internet_Type                  0
Online_Security                0
Online_Backup                  0
Device_Protection_Plan         0
Premium_Support                0
Streaming_TV                   0
Streaming_Movies               0
Streaming_Music                0
Unlimited_Data                 0
Contract                       0
Paperless_Billing              0
Payment_Method                 0
Monthly_Charge                 0
Total_Charges                  0
Total_Refunds                  0
Total_Extra_Data_Charges       0
Total_Long_Distance_Charges    0
Total_Revenue                  0
Customer_Status                0
Churn_Category                 0
Churn_Reason                   0
dtype: int64

In [6]:
#label encoding of Customer Status
print(df['Customer_Status'].value_counts())

Customer_Status
Stayed     4275
Churned    1732
Joined      411
Name: count, dtype: int64

In [7]:
print(df['Customer_Status'].unique())

df['Customer_Status'] = df['Customer_Status'].map({
    'Stayed': 0,
    'Joined': 0,
    'Churned': 1
})

print(df['Customer_Status'].value_counts())

['Stayed' 'Joined' 'Churned']
Customer_Status
0    4686
1    1732
Name: count, dtype: int64

In [8]:
#exclude textual data which does not need one hot encoding
df = df.drop(
    columns=[
        'Churn_Category',
        'Churn_Reason'
    ]
)

In [9]:
#set X and y such that in X, exclude Customer_ID(does not need one hot encoding) and Customer Status (target, assigned to y)
X = df.drop(
    columns=[
        'Customer_Status',
        'Customer_ID'
    ]
)

y = df['Customer_Status']

In [10]:
#one hot encoding
X = pd.get_dummies(
    X,
    drop_first=True #reduce redundancy
)

In [11]:
#divide the dataset into training data and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y #both sets preserve original distribution
)

In [12]:
#grouping numerical columns
numeric_cols = [
    'Age',
    'Number_of_Referrals',
    'Tenure_in_Months',
    'Monthly_Charge',
    'Total_Charges',
    'Total_Refunds',
    'Total_Extra_Data_Charges',
    'Total_Long_Distance_Charges',
    'Total_Revenue'
]

In [13]:
#standardize the dataset
scaler = StandardScaler()

X_train = X_train.copy()
X_test = X_test.copy()

X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

In [14]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=5000),
    "Random Forest": RandomForestClassifier(random_state=42),
    "Extra Trees": ExtraTreesClassifier(random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42),
    "KNN": KNeighborsClassifier(),
    "Naive Bayes": GaussianNB()
}

results = []

for name, model in models.items():

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    y_prob = model.predict_proba(X_test)[:, 1]

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),      # Correct predictions out of total predictions
        "Precision": precision_score(y_test, y_pred),    # Predicted positives that are actually positive
        "Recall": recall_score(y_test, y_pred),          # Actual positives correctly identified
        "F1 Score": f1_score(y_test, y_pred),            # Balance between precision and recall
        "ROC-AUC": roc_auc_score(y_test, y_prob)         # Ability to distinguish between the two classes
    })

results_df = pd.DataFrame(results)

results_df["Overall Score"] = (
    results_df["Accuracy"] +
    results_df["Precision"] +
    results_df["Recall"] +
    results_df["F1 Score"] +
    results_df["ROC-AUC"]
) / 5

best_model = results_df.sort_values(
    by="Overall Score",
    ascending=False
).iloc[0]

print(results_df.sort_values(by="Overall Score", ascending=False))

print("Chosen Model:", best_model["Model"])
print("Overall Score:", best_model["Overall Score"])

                 Model  Accuracy  Precision    Recall  F1 Score   ROC-AUC  \
0  Logistic Regression  0.841900   0.725000  0.668588  0.695652  0.891406
3    Gradient Boosting  0.840343   0.744828  0.622478  0.678179  0.897828
2          Extra Trees  0.829439   0.719178  0.605187  0.657277  0.885145
1        Random Forest  0.830997   0.742537  0.573487  0.647154  0.886928
5          Naive Bayes  0.771807   0.552529  0.818444  0.659698  0.865820
4                  KNN  0.791277   0.621538  0.582133  0.601190  0.808247

   Overall Score
0       0.764509
3       0.756731
2       0.739245
1       0.736221
5       0.733660
4       0.680877
Chosen Model: Logistic Regression
Overall Score: 0.7645093652642846

In [15]:
# Train the chosen Logistic Regression model
model = LogisticRegression(max_iter=5000, random_state=42)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

In [16]:
#Class labels: 0 - Not Churned, 1 - Churned
print("Classes:", model.classes_)

Classes: [0 1]

In [17]:
# Keep only active customers
active_df = df[df["Customer_Status"] == 0].copy()

In [18]:
# Save Customer IDs for the final output
customer_ids = active_df["Customer_ID"]

In [19]:
# Create prediction dataset
predict_df = active_df.drop(
    columns=[
        "Customer_ID",
        "Customer_Status"
    ]
)

In [20]:
#ensuring that the prediction dataset has the same columns and order as the original dataset used to train the model
predict_df = predict_df.reindex(
    columns=X.columns,
    fill_value=0
)

In [21]:
predict_df[numeric_cols] = scaler.transform(
    predict_df[numeric_cols]
)

In [22]:
#Churn Probability prediction
churn_prob = model.predict_proba(predict_df)[:, 1]

In [23]:
#Assigning risk
def risk(prob):

    if prob >= 0.60:
        return "High"

    elif prob >= 0.30:
        return "Medium"

    else:
        return "Low"

In [24]:
risk_labels = [
    risk(x)
    for x in churn_prob
]

In [25]:
final_df = pd.DataFrame({
    "Customer_ID": customer_ids.values
})

In [26]:
final_df['Churn_Probability'] = (
    churn_prob * 100
).round(2)

final_df['Risk_Category'] = risk_labels

In [27]:
high_risk = (
    final_df['Risk_Category']
    == 'High'
).sum()

print(
    "High Risk Customers:",
    high_risk
)

High Risk Customers: 324

In [30]:
final_df.shape

(4686, 3)

In [28]:
top20 = final_df.sort_values(
    by='Churn_Probability',
    ascending=False
)

top20[
    [
        'Customer_ID',
        'Churn_Probability',
        'Risk_Category'
    ]
].head(20)

     Customer_ID  Churn_Probability Risk_Category
3938   25733-HAR              77.67          High
4070   31232-KER              77.09          High
3998   85293-UTT              77.06          High
4266   42682-MAH              76.82          High
3464   85186-MAD              76.61          High
3218   62096-KAR              74.15          High
3568   75641-PUN              73.85          High
1062   17481-MAD              73.73          High
3929   39623-HAR              73.66          High
4280   65509-DEL              73.39          High
3195   14750-KAR              73.28          High
4096   92753-JHA              72.85          High
3272   97739-GUJ              72.83          High
3590   79777-MAH              72.34          High
3559   72971-TAM              72.07          High
3954   76233-BIH              71.92          High
3915   91505-DEL              71.81          High
4290   48033-MAH              71.56          High
4232   72002-UTT              71.40          High
3986   95624-KAR              71.29          High

In [29]:
importance = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_[0]
})

importance = importance.sort_values(
    by='Coefficient',
    ascending=False
)

importance.head(20)

                        Feature  Coefficient
17        State_Jammu & Kashmir     1.156524
24             State_Puducherry     0.548943
11                  State_Assam     0.519386
64  Payment_Method_Mailed Check     0.511504
18              State_Jharkhand     0.429716
62        Paperless_Billing_Yes     0.358098
3                Monthly_Charge     0.352467
0                           Age     0.270069
42    Internet_Type_Fiber Optic     0.267412
44           Online_Security_No     0.242132
50           Premium_Support_No     0.187360
57          Streaming_Music_Yes     0.140434
46             Online_Backup_No     0.136698
53             Streaming_TV_Yes     0.110397
55         Streaming_Movies_Yes     0.098305
40         Internet_Service_Yes     0.080921
6      Total_Extra_Data_Charges     0.072640
26              State_Rajasthan     0.067005
49   Device_Protection_Plan_Yes     0.063157
59           Unlimited_Data_Yes     0.057443

In [32]:
final_df.to_csv(
    "Telcom_Churn_Predictions.csv",
    index=False
)

print("Export Complete")

Export Complete