In [1]:
import os
os.listdir("Downloads")

['14074_2026_05_22.pdf',
 '14076_2026_05_22.pdf',
 '1st question.jpeg',
 '31414_2026_04_29.pdf',
 '31414_2026_05_22.pdf',
 '45365_2026_05_22.pdf',
 '96798_2026_05_22.pdf',
 'Anaconda3-2025.12-2-Windows-x86_64.exe',
 'archive.zip',
 'Bubble_sort (1).exe',
 'Bubble_sort.exe',
 'Canva Setup 1.113.0.exe',
 'ChromeSetup.exe',
 'Churn Analysis.pbix',
 'CiscoPacketTracer_900_win_64bit.exe',
 'COA AAT Report format 2025-26.docx',
 'coa project (1).docx',
 'coa project.docx',
 'COA UNIT-2 PART-4.ppt',
 'COA UNIT-2 PART-4.ppt.pdf',
 'coareport (1).docx',
 'coareport.docx',
 'codeblocks-25.03mingw-setup.exe',
 'codeblocks_25.03.tar.xz',
 'comet_installer_latest.exe',
 'company-sales (1).csv',
 'company-sales.csv',
 'cpp_tutorial',
 'Customer_Data.csv',
 'Data-Resources.zip',
 'desktop.ini',
 'fwd_lab_exam_PPT (1).pptx.pptx',
 'Git-2.54.0-64-bit.exe',
 'GitHubDesktopSetup-x64.exe',
 'Hands-On_Machine_Learning_with_Scikit-Learn-Keras-and-TensorFlow-2nd-Edition-Aurelien-Geron.pdf',
 'java 3rd sem',
 'jgrasp-2.0.6.10-installer.exe',
 'jgrasp-2.0.6.10-installer_NU2-Av1.exe',
 'maths (1).pdf',
 'maths.pdf',
 'Miniconda3-latest-Windows-x86_64.exe',
 'msys2-x86_64-20241208.exe',
 'Mybooks',
 'mysql-workbench-community-8.0.44-winx64 (1).msi',
 'normal_table.pdf',
 'notes of 3rd sem',
 'Notion Setup 4.18.1.exe',
 'OfficeSetup.exe',
 'OperaGXSetup (1).exe',
 'OperaGXSetup (2).exe',
 'OperaGXSetup (3).exe',
 'OperaGXSetup.exe',
 'OperaSetup (1).exe',
 'OperaSetup.exe',
 'oracle-ai-database-free-26ai-23.26.0-1.el8.x86_64.rpm',
 'Oracle_AI_Database_26ai_Free.ova',
 'output',
 'planets.csv',
 'projectr1.pdf',
 'python-3.13.7-amd64.exe',
 'SQL2025-SSEI-Expr.exe',
 'student-performance-dataset.ipynb',
 'Untitled1 (1).ipynb',
 'Untitled1.ipynb',
 'v7.5.4 source code.zip',
 'VirtualBox-7.2.4-170995-Win.exe',
 'VSCodeUserSetup-x64-1.103.2 (1).exe',
 'VSCodeUserSetup-x64-1.103.2.exe',
 'vs_SSMS.exe',
 'Week 3 (1).pdf',
 'Week 3.pdf',
 'Week 4.pdf',
 'Week 6 (1) (1).pdf',
 'Week 6 (1).pdf',
 'WhatsApp Audio 2025-11-24 at 22.09.27_c1308c08.opus',
 'wsl_update_arm64.msi',
 'wsl_update_x64.msi']

In [2]:
import pandas as pd
data=pd.read_csv("Downloads/Customer_Data.csv")
data.head()

,Customer_ID,Gender,Age,Married,State,Number_of_Referrals,Tenure_in_Months,Value_Deal,Phone_Service,Multiple_Lines,...,Payment_Method,Monthly_Charge,Total_Charges,Total_Refunds,Total_Extra_Data_Charges,Total_Long_Distance_Charges,Total_Revenue,Customer_Status,Churn_Category,Churn_Reason
0,19877-DEL,Male,35,No,Delhi,7,27,NaN,Yes,No,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,58353-MAH,Female,45,Yes,Maharashtra,14,13,NaN,Yes,Yes,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,25063-WES,Male,51,No,West Bengal,4,35,Deal 5,Yes,No,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,59787-KAR,Male,79,No,Karnataka,3,21,Deal 4,Yes,No,...,Bank Withdrawal,98.0,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,28544-TAM,Female,80,No,Tamil Nadu,3,8,NaN,Yes,No,...,Credit Card,83.9,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6418 entries, 0 to 6417
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Customer_ID                  6418 non-null   object
 1   Gender                       6418 non-null   object
 2   Age                          6418 non-null   int64
 3   Married                      6418 non-null   object
 4   State                        6418 non-null   object
 5   Number_of_Referrals          6418 non-null   int64
 6   Tenure_in_Months             6418 non-null   int64
 7   Value_Deal                   2870 non-null   object
 8   Phone_Service                6418 non-null   object
 9   Multiple_Lines               5796 non-null   object
 10  Internet_Service             6418 non-null   object
 11  Internet_Type                5028 non-null   object
 12  Online_Security              5028 non-null   object
 13  Online_Backup                5028 non-null   object
 14  Device_Protection_Plan       5028 non-null   object
 15  Premium_Support              5028 non-null   object
 16  Streaming_TV                 5028 non-null   object
 17  Streaming_Movies             5028 non-null   object
 18  Streaming_Music              5028 non-null   object
 19  Unlimited_Data               5028 non-null   object
 20  Contract                     6418 non-null   object
 21  Paperless_Billing            6418 non-null   object
 22  Payment_Method               6418 non-null   object
 23  Monthly_Charge               6418 non-null   float64
 24  Total_Charges                6418 non-null   float64
 25  Total_Refunds                6418 non-null   float64
 26  Total_Extra_Data_Charges     6418 non-null   int64
 27  Total_Long_Distance_Charges  6418 non-null   float64
 28  Total_Revenue                6418 non-null   float64
 29  Customer_Status              6418 non-null   object
 30  Churn_Category               1732 non-null   object
 31  Churn_Reason                 1732 non-null   object
dtypes: float64(5), int64(4), object(23)
memory usage: 1.6+ MB

In [4]:
data.isnull().sum()

Customer_ID                       0
Gender                            0
Age                               0
Married                           0
State                             0
Number_of_Referrals               0
Tenure_in_Months                  0
Value_Deal                     3548
Phone_Service                     0
Multiple_Lines                  622
Internet_Service                  0
Internet_Type                  1390
Online_Security                1390
Online_Backup                  1390
Device_Protection_Plan         1390
Premium_Support                1390
Streaming_TV                   1390
Streaming_Movies               1390
Streaming_Music                1390
Unlimited_Data                 1390
Contract                          0
Paperless_Billing                 0
Payment_Method                    0
Monthly_Charge                    0
Total_Charges                     0
Total_Refunds                     0
Total_Extra_Data_Charges          0
Total_Long_Distance_Charges       0
Total_Revenue                     0
Customer_Status                   0
Churn_Category                 4686
Churn_Reason                   4686
dtype: int64

In [5]:
data["Customer_Status"].value_counts()

Customer_Status
Stayed     4275
Churned    1732
Joined      411
Name: count, dtype: int64

In [6]:
data["Value_Deal"].value_counts(dropna=False)

Value_Deal
NaN       3548
Deal 2     758
Deal 5     738
Deal 4     540
Deal 1     469
Deal 3     365
Name: count, dtype: int64

In [7]:
data.describe()

,Age,Number_of_Referrals,Tenure_in_Months,Monthly_Charge,Total_Charges,Total_Refunds,Total_Extra_Data_Charges,Total_Long_Distance_Charges,Total_Revenue
count,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000,6418.000000
mean,47.070739,7.427859,17.342786,63.652867,2280.374858,1.924944,6.718604,748.703468,3033.871987
std,16.703633,4.621519,10.576391,31.188823,2268.049985,7.849083,24.722533,847.672844,2866.505426
min,18.000000,0.000000,1.000000,-10.000000,18.800000,0.000000,0.000000,0.000000,21.360000
25%,33.000000,3.000000,8.000000,30.562500,395.725000,0.000000,0.000000,70.805000,603.742500
50%,46.000000,7.000000,16.000000,70.100000,1396.125000,0.000000,0.000000,407.475000,2108.635000
75%,60.000000,11.000000,27.000000,89.750000,3783.600000,0.000000,0.000000,1182.917500,4801.537500
max,85.000000,15.000000,36.000000,118.750000,8684.800000,49.790000,150.000000,3564.720000,11979.340000

In [8]:
data.columns

Index(['Customer_ID', 'Gender', 'Age', 'Married', 'State',
       'Number_of_Referrals', 'Tenure_in_Months', 'Value_Deal',
       'Phone_Service', 'Multiple_Lines', 'Internet_Service', 'Internet_Type',
       'Online_Security', 'Online_Backup', 'Device_Protection_Plan',
       'Premium_Support', 'Streaming_TV', 'Streaming_Movies',
       'Streaming_Music', 'Unlimited_Data', 'Contract', 'Paperless_Billing',
       'Payment_Method', 'Monthly_Charge', 'Total_Charges', 'Total_Refunds',
       'Total_Extra_Data_Charges', 'Total_Long_Distance_Charges',
       'Total_Revenue', 'Customer_Status', 'Churn_Category', 'Churn_Reason'],
      dtype='object')

In [9]:
#importing libraries
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [10]:
customer_id=data["Customer_ID"]

In [11]:
#drop columns that are useless(customer id) for prediction and causes data leakage(cutomer category and reason) 
data=data.drop(columns=["Customer_ID","Churn_Category","Churn_Reason"])

In [12]:
#handle the column value_deal missing values
data["Value_Deal"]=data["Value_Deal"].fillna("No Deal")

In [13]:
data.head(10)

,Gender,Age,Married,State,Number_of_Referrals,Tenure_in_Months,Value_Deal,Phone_Service,Multiple_Lines,Internet_Service,...,Contract,Paperless_Billing,Payment_Method,Monthly_Charge,Total_Charges,Total_Refunds,Total_Extra_Data_Charges,Total_Long_Distance_Charges,Total_Revenue,Customer_Status
0,Male,35,No,Delhi,7,27,No Deal,Yes,No,Yes,...,One Year,Yes,Credit Card,65.60,593.30,0.00,0,381.51,974.81,Stayed
1,Female,45,Yes,Maharashtra,14,13,No Deal,Yes,Yes,Yes,...,Month-to-Month,No,Credit Card,-4.00,542.40,38.33,10,96.21,610.28,Stayed
2,Male,51,No,West Bengal,4,35,Deal 5,Yes,No,Yes,...,Month-to-Month,Yes,Bank Withdrawal,73.90,280.85,0.00,0,134.60,415.45,Churned
3,Male,79,No,Karnataka,3,21,Deal 4,Yes,No,Yes,...,Month-to-Month,Yes,Bank Withdrawal,98.00,1237.85,0.00,0,361.66,1599.51,Churned
4,Female,80,No,Tamil Nadu,3,8,No Deal,Yes,No,Yes,...,Month-to-Month,Yes,Credit Card,83.90,267.40,0.00,0,22.14,289.54,Churned
5,Male,24,No,Telangana,9,2,Deal 5,Yes,No,Yes,...,Month-to-Month,Yes,Credit Card,69.40,571.45,0.00,0,150.93,722.38,Stayed
6,Female,66,Yes,Maharashtra,9,23,Deal 1,Yes,No,Yes,...,Two Year,Yes,Bank Withdrawal,109.70,7904.25,0.00,0,707.16,8611.41,Stayed
7,Male,51,Yes,Gujarat,12,24,Deal 2,Yes,Yes,Yes,...,Two Year,Yes,Credit Card,84.65,5377.80,0.00,20,816.48,6214.28,Stayed
8,Female,63,No,Gujarat,4,10,Deal 5,Yes,No,Yes,...,Two Year,Yes,Bank Withdrawal,48.20,340.35,0.00,0,73.71,414.06,Stayed
9,Female,41,No,Uttar Pradesh,3,1,No Deal,Yes,Yes,Yes,...,Two Year,Yes,Credit Card,90.45,5957.90,0.00,0,1849.90,7807.80,Stayed

In [14]:
#encode categorical(object/text dtype)columns
#2->stayed,0->churned,1->joined
le=LabelEncoder()
for col in data.select_dtypes(include="object").columns:
    data[col]=le.fit_transform(data[col])

In [15]:
x=data.drop("Customer_Status",axis=1)
y=data["Customer_Status"]

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [22]:
rf_model=RandomForestClassifier(n_estimators=100,random_state=42)
lr_model=LogisticRegression(max_iter=7000,random_state=42)

models={
    "Random Forest": rf_model,
    "Logistic Regression": lr_model
}

In [23]:
for name,model in models.items():
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    accuracy=accuracy_score(y_test,y_pred)
    print(name)
    print(f"Accuracy={accuracy:.4f}")
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))

Random Forest
Accuracy=0.8341
[[183  16 120]
 [ 35  52   2]
 [ 38   2 836]]
              precision    recall  f1-score   support

           0       0.71      0.57      0.64       319
           1       0.74      0.58      0.65        89
           2       0.87      0.95      0.91       876

    accuracy                           0.83      1284
   macro avg       0.78      0.70      0.73      1284
weighted avg       0.82      0.83      0.83      1284

Logistic Regression
Accuracy=0.8022
[[192  27 100]
 [ 22  53  14]
 [ 90   1 785]]
              precision    recall  f1-score   support

           0       0.63      0.60      0.62       319
           1       0.65      0.60      0.62        89
           2       0.87      0.90      0.88       876

    accuracy                           0.80      1284
   macro avg       0.72      0.70      0.71      1284
weighted avg       0.80      0.80      0.80      1284

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 7000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=7000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [20]:
feature_importance = pd.DataFrame({
    "Feature": x.columns,
    "Importance": rf_model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

print(feature_importance.head(10))

                        Feature  Importance
27                Total_Revenue    0.145661
23                Total_Charges    0.135811
19                     Contract    0.103188
26  Total_Long_Distance_Charges    0.088114
22               Monthly_Charge    0.079116
1                           Age    0.066346
5              Tenure_in_Months    0.048547
3                         State    0.044346
4           Number_of_Referrals    0.041125
11              Online_Security    0.029719

In [27]:
results=pd.DataFrame()
results["Customer_ID"]=customer_id.loc[x_test.index]
results["Actual_Status"]=y_test
results["Predicted_Status"]=y_pred
results.reset_index(drop=True,inplace=True)
results.head(10)

  Customer_ID  Actual_Status  Predicted_Status
0   87940-UTT              2                 2
1   45159-WES              2                 2
2   59258-ODI              2                 2
3   34947-UTT              2                 2
4   46241-KER              2                 2
5   24632-TAM              2                 2
6   43271-DEL              2                 2
7   44639-UTT              2                 2
8   21722-AND              2                 2
9   28033-ASS              2                 0

In [28]:
results.to_csv("churn_predictions.csv",index=False)

In [29]:
results.shape

(1284, 3)

In [30]:
results.head()

  Customer_ID  Actual_Status  Predicted_Status
0   87940-UTT              2                 2
1   45159-WES              2                 2
2   59258-ODI              2                 2
3   34947-UTT              2                 2
4   46241-KER              2                 2